name: CI Pipeline - Cryptobank

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests with Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=postgres" >> .env
          echo "POSTGRES_PASSWORD=postgres" >> .env
          echo "POSTGRES_DB=cryptobank" >> .env
          echo "DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cryptobank" >> .env

      - name: Start Containers
        run: docker-compose up -d --build

      - name: Wait for DB
        run: sleep 10

      - name: Run Migrations
        run: docker-compose exec -T app alembic upgrade head

      - name: Run Tests
        run: docker-compose exec -T app pytest -v